site_name: Pivotal Alumni Codex
repo_url: https://github.com/alumni-codex/alumni-codex.github.io
theme:
  name: material
  features:
    - search
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
  font:
    code: Ubuntu Mono
    text: Source Sans Pro
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Design Topics: design/index.md
  - Engineering Topics:
      - Tech Videos: engineering/tech-videos.md
      - Core Practice Discussions: engineering/core-practice.md
  - Product Topics: product/index.md
  - Agility Resources:
      - Practices: agility-resources/practices.md
      - Project Management: agility-resources/project-management.md
      - Job Hunting: agility-resources/job_hunting.md
  - Labs-like Consultancies: consultancies.md
  - Pivotal Website Archive: archives.md
  - Stories of History:
      - The Pivotal Squirrel: history/squirrel.md
      - The Nuts of Onsi's People: history/nuts.md
  # Please keep this as the bottom-most link
  - Contributing: contributing/index.md
